spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: deLamba_dev
      username: admin
      password: admin123
      authentication-database: admin

logging:
  level:
    root: INFO
    com.delivery: DEBUG
    org.springframework.data.mongodb: DEBUG